---
language: ruby
sudo: false
before_install: gem install bundler
bundler_args: --without development acceptancetests --jobs=3 --retry=3 --no-deployment
cache: bundler
script: bundle exec rake spec
rvm:
 - '2.1'
 - '2.3'
 - '2.4'
